config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resource :transfers, only: [:new, :create]
  resource :improved_transfers, only: [:new, :create]
end

app/models/account.rb
class Account < ActiveRecord::Base
  include Awareness

  belongs_to :user

  validates :balance, presence: true,
                      numericality: { only_integer: true, greater_than: 10 }
  validates :bonus_points, presence: true,
                     numericality: { only_integer: true, less_than: 1000 }

  scope :owned_by_others, ->(user_id) { where.not(user_id: user_id) }

  def to_s
    "Account ##{id}"
  end
end

app/models/transfering_system.rb
class TransferingSystem #< ActiveRecord::Base
  include Awareness
end

app/models/user.rb
class User < ActiveRecord::Base
  include Awareness

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :accounts, dependent: :destroy
end

app/models/users/admin_user.rb
class AdminUser < User
end

app/models/users/regular_user.rb
class RegularUser < User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def go_to(resource_or_action)
    case resource_or_action
    when Symbol then
      render resource_or_action
    else
      redirect_to resource_or_action
    end
  end

  alias_method :display_error, :go_to
end

app/controllers/improved_transfers_controller.rb
class ImprovedTransfersController < ApplicationController
  include Awareness

  before_action :authenticate_user!

  def new
    @transfer = ImprovedMoneyTransfering.new(self)
  end

  def create
    @transfer = ImprovedMoneyTransfering.new(self, improved_transfers_params)
    @transfer.perform
  end

  private

  def improved_transfers_params
    params.require(:improved_money_transfering)
          .permit(:source_id, :destination_id, :amount)
  end
end

app/controllers/transfers_controller.rb
class TransfersController < ApplicationController
  before_action :authenticate_user!

  def new
    @transfer = MoneyTransfering.new(self)
  end

  def create
    @transfer = MoneyTransfering.new(self, transfers_params)
    @transfer.perform
  end

  private

  def transfers_params
    params.require(:money_transfering)
          .permit(:source_id, :destination_id, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/improved_transfers/_account.html.slim
tr
  td = account
  td = account.balance
  td = account.bonus_points

app/views/improved_transfers/new.html.slim
table
  thead
    tr
      th Account
      th Balance
      th Bonus points
  tbody
    = render partial: 'account', collection: Account.all

br

= simple_form_for @transfer, url: improved_transfers_path do |f|
  - if @transfer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@transfer.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @transfer.errors.full_messages.each do |msg|
          li = msg

  = f.input :source_id, as: :select, collection: current_user.accounts, label: 'source', selected: 1
  = f.input :destination_id, as: :select, collection: Account.owned_by_others(current_user.id), label: 'destination', selected: 1
  = f.input :amount
  = f.submit :send

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsContexts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/transfers/_account.html.slim
tr
  td = account
  td = account.balance
  td = account.bonus_points

app/views/transfers/new.html.slim
table
  thead
    tr
      th Account
      th Balance
      th Bonus points
  tbody
    = render partial: 'account', collection: Account.all

br

= simple_form_for @transfer, url: transfers_path do |f|
  - if @transfer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@transfer.errors.count, "error")} prohibited this task from being saved:"
      ul
        - @transfer.errors.full_messages.each do |msg|
          li = msg

  = f.input :source_id, as: :select, collection: current_user.accounts, label: 'source', selected: 1
  = f.input :destination_id, as: :select, collection: Account.owned_by_others(current_user.id), label: 'destination', selected: 1
  = f.input :amount
  = f.submit :send